services:
  - name: photos-map
    env:
      - name: NODE_ENV
        value: production
      - name: DATABASE_URL
        fromDatabase:
          name: database
          query: SELECT connection_uri FROM credentials WHERE connection_uri LIKE 'sqlite://%'
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: SESSION_SECRET
        fromDatabase:
          name: photos-map
          query: SELECT session_secret FROM env_vars LIMIT 1

databases:
  - name: database
    type: sqlite
    disk: 10

routes:
  - path: /
    command: static
    dir: public
  - path: /public
    command: static
    dir: public
  - path: /uploads
    command: static
    dir: uploads
